language: rust

rust:
- stable
- beta
- nightly

script:
- cargo test

matrix:
  include:
  - os: osx

  - name: docs.rs
    rust: nightly
    script:
    - RUSTDOCFLAGS='--cfg=docsrs -Dwarnings' cargo doc --no-deps

  - name: cargo fmt
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt --all -- --check

  - name: cargo clippy
    install:
    - rustup component add clippy
    script:
    - cargo clippy --all --all-targets -- -D warnings

branches:
  only: [staging, trying, master]
